### ISSUE TITLE
Inference cpu Docker container

### ISSUE THREAD

**Issue by akromeo** [NOEL-MNI/deepFCD#25]
I am trying to run the inference cpu docker container however I am running into an issue that it is not setting the BRAIN_MASKING environ variable correctly and therefore not importing brain_extraction function in the image_processing script. 

Error: /tmp/zou_2519.log - No such file or directory.
loading nifti files
registration to MNI template space
performing N3 bias correction
performing brain extraction using ANTsPyNet
Traceback (most recent call last):
  File "/app/preprocess.py", line 94, in <module>
    noelImageProcessor(
  File "/app/deepMask/app/utils/image_processing.py", line 440, in pipeline
    self.__skull_stripping()
  File "/app/deepMask/app/utils/image_processing.py", line 181, in __skull_stripping
    prob = brain_extraction(self._t1_n4, modality="t1")
NameError: name 'brain_extraction' is not defined

I am running the Docker image on my Mac OS w M3 processor.  

Thanks

**Comment by ravnoor** [comment]
Could you please fill out the following information, and the actual command executed?

## Your Environment

* Version used (e.g. v1.1.1 or commit hash):
* Environment name and version [e.g. Docker (noelmni/deep-fcd:v1.1.2), M1/Intel macOS 14.2.1 with Conda (Python 3.7), Linux (Conda 4.11 w/ Python 3.7)]:
* Hardware (e.g., 4 vCPUs, 16GB RAM, NVIDIA TITAN RTX w/ 24GB VRAM)
* Using GPU or CPU:
* Operating System (OS) and version (if not using the Docker image; e.g. Ubuntu 22.04.4 LTS):
* OS baremetal or virtualized:

**Comment by akromeo** [comment]
This is the docker command I used except I replaced $PWD w my directory.  CA was the subject ID:

$ docker run --rm -it --init --env OMP_NUM_THREADS=6 --volume=$PWD/io:/io noelmni/deep-fcd:latest /app/inference.py CA T1.nii.gz Flair.nii.gz /io cpu 1 1

Not sure what version this is.  Version is latest?  I don’t know how to tell which docker image version that is pulling.  

I am running this on my Mac OS M3 cpu but I am using the docker container which uses ubuntu base image.
